type = "terminal" # terminal or file
format = "full" # full or compact
source_location = "module_and_line" # none or module_and_line
timezone = "utc" # utc or local
level = "debug" # one of trace, debug, info, warning, error, critical
destination = "stderr" # stderr or stdout

[filter_config]
# This type of filter will pass any message that has
# - severity at least always_pass_on_severity_at_least
#   OR
# - any of the [[filter_config.passes]] key and value pair matches any of the
# message key and value pair AND severity is at least severity_at_least
type = "PassOnAnyOf"
always_pass_on_severity_at_least = "debug"

[[filter_config.passes]]
key = "key1"
value = "value1"
severity_at_least = "trace"

[[filter_config.passes]]
key = "key2"
value = "value2"
severity_at_least = "debug"